random()

In [1]:
import numpy as np

In [2]:
np.random.random()

0.588680607206973

In [4]:
np.random.random((2,3))

array([[0.87155233, 0.70427441, 0.31016405],
       [0.56050686, 0.02096721, 0.68587371]])

In [5]:
np.random.random(2)

array([0.85621878, 0.13620907])

In [6]:
np.random.randint(1,10)

5

In [7]:
np.random.randint(1,10,(2,2))

array([[8, 7],
       [1, 8]])

In [9]:
np.random.randint(1,10,(3,3))

array([[4, 5, 8],
       [8, 7, 8],
       [6, 9, 3]])

In [10]:
np.random.rand(2,2)

array([[0.09522254, 0.00387616],
       [0.91469968, 0.19507683]])

In [11]:
np.random.randn(2,2)

array([[-0.22028255, -1.14947383],
       [ 0.13969949,  0.87959613]])

In [12]:
a=np.arange(1,10)
a

array([1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.random.choice(a)

8