In [2]:
import numpy as np

In [3]:
lst=[1,2,3,4,5]
print(lst)

[1, 2, 3, 4, 5]


In [4]:
print("1D ARRAY")
a=np.array([1,2,3,4,5])
print(a)
print("2D ARRAY")
b=np.array([[1,2,3,4,5],
            [6,7,8,9,10]])
print(b)
print("3D ARRAY")

c=np.array([[1,2,3,4,5],
            [6,7,8,9,10],
            [11,1,2,3,1]])
print(c)

1D ARRAY
[1 2 3 4 5]
2D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]
3D ARRAY
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11  1  2  3  1]]


In [5]:
print(a.size,b.size,c.size) #gives number of elements

5 10 15


In [6]:
print(a.shape,b.shape,c.shape) #gives number of rows and number of columns

(5,) (2, 5) (3, 5)


In [7]:
print(c.dtype)

int32


In [8]:
c.transpose()   #rows becomes column ,column becomes rows

array([[ 1,  6, 11],
       [ 2,  7,  1],
       [ 3,  8,  2],
       [ 4,  9,  3],
       [ 5, 10,  1]])

np.empty((rows,cols),dtype)

In [9]:
np.empty((4,4),dtype=float)

array([[6.23042070e-307, 4.67296746e-307, 1.69121096e-306,
        1.60219578e-306],
       [8.34441742e-308, 1.78022342e-306, 6.23058028e-307,
        9.79107872e-307],
       [6.89807188e-307, 7.56594375e-307, 6.23060065e-307,
        1.78021527e-306],
       [8.34454050e-308, 1.11261027e-306, 1.15706896e-306,
        1.33512173e-306]])

In [10]:
x=np.ones(6)
x

array([1., 1., 1., 1., 1., 1.])

In [12]:
y=np.ones((3,5))
y

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [14]:
y=np.ones((3,5),dtype=int)
y

array([[1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1],
       [1, 1, 1, 1, 1]])

In [19]:
z=np.zeros((3,4))
z

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [18]:
a=np.zeros((3,4),dtype=str)
a

array([['', '', '', ''],
       ['', '', '', ''],
       ['', '', '', '']], dtype='<U1')

# arrange()
np.arange(start,end,step)

In [21]:
a=np.arange(1,20)
a

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16, 17,
       18, 19])

In [28]:
#a=np.arange(1,step=9,stop=90)
a=np.arange(1,99,9)
#np.arange(start,end,step)
a

array([ 1, 10, 19, 28, 37, 46, 55, 64, 73, 82, 91])

# reshape()
arr.reshape((rows,cols))

In [32]:
a=np.arange(2,20,2)
a=a.reshape((3,3))
a

array([[ 2,  4,  6],
       [ 8, 10, 12],
       [14, 16, 18]])

In [33]:
b=np.arange(1,100,2)
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [35]:
b.reshape((10,5))

array([[ 1,  3,  5,  7,  9],
       [11, 13, 15, 17, 19],
       [21, 23, 25, 27, 29],
       [31, 33, 35, 37, 39],
       [41, 43, 45, 47, 49],
       [51, 53, 55, 57, 59],
       [61, 63, 65, 67, 69],
       [71, 73, 75, 77, 79],
       [81, 83, 85, 87, 89],
       [91, 93, 95, 97, 99]])

In [36]:
b=b.flatten()
b

array([ 1,  3,  5,  7,  9, 11, 13, 15, 17, 19, 21, 23, 25, 27, 29, 31, 33,
       35, 37, 39, 41, 43, 45, 47, 49, 51, 53, 55, 57, 59, 61, 63, 65, 67,
       69, 71, 73, 75, 77, 79, 81, 83, 85, 87, 89, 91, 93, 95, 97, 99])

In [37]:
a=a.ravel()
a

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

a.ravel():(i)Return only reference/view of original array (II) if you modify the array you would notice that the value of original array also changes.(iii) Ravel is faster than flatten() as it doesnot occupy any memory. (iv)Ravel is a library-level function

a.flatten():(i)Return copy of original array (ii)if you modify any value of this array value of original array is not  affected.(iii) Flatten() is comparatively slower than ravel() as it occupies memory.(iv)Flatten is a method of an ndarray object

In [38]:
# numpy array slicing
a=np.arange(1,51)
a=a.reshape(10,5)
a

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [40]:
a[0]


array([1, 2, 3, 4, 5])

In [41]:
a[1]

array([ 6,  7,  8,  9, 10])

In [42]:
a[0,0]

1

In [43]:
a[3,4]

20

In [44]:
a[2:5] #2nd row to 4th row

array([[11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25]])

In [48]:
a[0:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [49]:
a[:,2] #: means all the rows of 2nd column

array([ 3,  8, 13, 18, 23, 28, 33, 38, 43, 48])

In [51]:
a[2:5,4] #prints upto 2nd row to 5th row of 4th column

array([15, 20, 25])

In [52]:
a[:,:]

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10],
       [11, 12, 13, 14, 15],
       [16, 17, 18, 19, 20],
       [21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30],
       [31, 32, 33, 34, 35],
       [36, 37, 38, 39, 40],
       [41, 42, 43, 44, 45],
       [46, 47, 48, 49, 50]])

In [54]:
a[:,2:5] #all the rows from 2 to 5th column

array([[ 3,  4,  5],
       [ 8,  9, 10],
       [13, 14, 15],
       [18, 19, 20],
       [23, 24, 25],
       [28, 29, 30],
       [33, 34, 35],
       [38, 39, 40],
       [43, 44, 45],
       [48, 49, 50]])

In [55]:
a[:,2:5].dtype

dtype('int32')

Numpy Mathematical Operation

In [59]:
a=np.arange(0,18).reshape((6,3))
b=np.arange(20,38).reshape((6,3))
print(a)
print(b)

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]
 [12 13 14]
 [15 16 17]]
[[20 21 22]
 [23 24 25]
 [26 27 28]
 [29 30 31]
 [32 33 34]
 [35 36 37]]


In [60]:
a+b

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [61]:
a*b


array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [62]:
np.add(a,b)

array([[20, 22, 24],
       [26, 28, 30],
       [32, 34, 36],
       [38, 40, 42],
       [44, 46, 48],
       [50, 52, 54]])

In [64]:
np.subtract(a,b)

array([[-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20],
       [-20, -20, -20]])

In [66]:
np.multiply(a,b) #its not matrix multiplication its simple multiplication

array([[  0,  21,  44],
       [ 69,  96, 125],
       [156, 189, 224],
       [261, 300, 341],
       [384, 429, 476],
       [525, 576, 629]])

In [67]:
np.divide(a,b)

array([[0.        , 0.04761905, 0.09090909],
       [0.13043478, 0.16666667, 0.2       ],
       [0.23076923, 0.25925926, 0.28571429],
       [0.31034483, 0.33333333, 0.35483871],
       [0.375     , 0.39393939, 0.41176471],
       [0.42857143, 0.44444444, 0.45945946]])

In [69]:
b=a.reshape((3,6))
b

array([[ 0,  1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10, 11],
       [12, 13, 14, 15, 16, 17]])

In [71]:
a.dot(b) #matrix multiplication

array([[ 30,  33,  36,  39,  42,  45],
       [ 84,  96, 108, 120, 132, 144],
       [138, 159, 180, 201, 222, 243],
       [192, 222, 252, 282, 312, 342],
       [246, 285, 324, 363, 402, 441],
       [300, 348, 396, 444, 492, 540]])

In [73]:
b.max()

17

In [74]:
b.min()

0

In [76]:
b.argmax()  #gives tha index of max value

17

In [77]:
b.argmin()

0

In [78]:
np.sum(b)

153

In [80]:
np.sum(b,axis=1)   #gives the sum of each row 15 is sum of first row,51 is second rows sum...

array([15, 51, 87])

In [81]:
np.sum(b,axis=0)

array([18, 21, 24, 27, 30, 33])

In [82]:
np.mean(b)

8.5

In [84]:
np.sqrt(b)

array([[0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
        2.23606798],
       [2.44948974, 2.64575131, 2.82842712, 3.        , 3.16227766,
        3.31662479],
       [3.46410162, 3.60555128, 3.74165739, 3.87298335, 4.        ,
        4.12310563]])

In [85]:
np.std(b)   #standard deviation

5.188127472091127

In [86]:
np.log(b)

C:\Users\siris\AppData\Local\Temp\ipykernel_22256\4200754868.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(b)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791],
       [1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509,
        2.39789527],
       [2.48490665, 2.56494936, 2.63905733, 2.7080502 , 2.77258872,
        2.83321334]])